// <auto-generated />
using System;
using Case_1_2.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Case_1_2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250918010114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Case_1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 9, 18, 1, 1, 14, 438, DateTimeKind.Utc).AddTicks(7090),
                            Description = "This is a sample product for testing",
                            Name = "Sample Product 1",
                            Price = 29.99m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 9, 18, 1, 1, 14, 438, DateTimeKind.Utc).AddTicks(7180)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Books",
                            CreatedAt = new DateTime(2025, 9, 18, 1, 1, 14, 438, DateTimeKind.Utc).AddTicks(7280),
                            Description = "Another sample product",
                            Name = "Sample Product 2",
                            Price = 49.99m,
                            Stock = 50,
                            UpdatedAt = new DateTime(2025, 9, 18, 1, 1, 14, 438, DateTimeKind.Utc).AddTicks(7280)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
